"""Authoritative legal source definitions for Wisconsin, Minnesota, and Federal overlay.

All entries are based on primary government and judicial providers.
Deep Coverage is reserved for evaluation-certified corpora.
"""

from __future__ import annotations

from datetime import date
from .jurisdiction_registry import (
    AcquisitionMethod,
    AcquisitionMode,
    AuthRequirement,
    AuthorityFamily,
    AuthorityLevel,
    AvailabilityStatus,
    CoverageStatus,
    GeographicScope,
    ImplementationStatus,
    JurisdictionSourceRegistry,
    LegalDomain,
    OfficialStatus,
    SourceDefinition,
    UpdateCadence,
    CurrentnessCapability,
)


WISCONSIN_SOURCES: tuple[SourceDefinition, ...] = (
    SourceDefinition(
        source_id="US-WI-CONST",
        jurisdiction="US-WI",
        geographic_scope=GeographicScope.STATEWIDE,
        legal_domain=LegalDomain.CONSTITUTIONAL,
        authority_family=AuthorityFamily.CONSTITUTION,
        source_name="Wisconsin Constitution",
        provider_name="Wisconsin State Legislature",
        official_status=OfficialStatus.OFFICIAL,
        authority_level=AuthorityLevel.PRIMARY_CONTROLLING,
        canonical_url="https://docs.legis.wisconsin.gov/constitution",
        acquisition_method=AcquisitionMethod.WEB_FETCH,
        acquisition_mode=AcquisitionMode.HTML_DOCUMENT,
        update_cadence=UpdateCadence.SESSIONAL,
        temporal_version_semantics="current_in_force_with_amendment_notes",
        effective_date_semantics="effective_upon_ratification",
        publication_date_semantics="certified_biennial_publication",
        parser_normalizer_id="wi_legis_html_v1",
        citation_syntax=("Wis. Const. art. {art}, § {sec}",),
        currentness_capability=CurrentnessCapability.OFFICIAL_BULLETIN,
        historical_version_capability=True,
        provenance_capability=True,
        auth_requirement=AuthRequirement.NONE,
        licensing_terms_notes="Public government work; Wisconsin Legislature open access terms.",
        availability_status=AvailabilityStatus.AVAILABLE,
        implementation_status=ImplementationStatus.VERIFIED,
        coverage_status=CoverageStatus.VERIFIED,
        last_verified_date=date(2026, 9, 8),
        verification_evidence="Verified live HTTP 200 via docs.legis.wisconsin.gov/constitution on 2026-09-08.",
        known_limitations=("Does not provide machine-readable diff API directly; HTML and PDF only.",),
    ),
    SourceDefinition(
        source_id="US-WI-STATUTES-CH48",
        jurisdiction="US-WI",
        geographic_scope=GeographicScope.STATEWIDE,
        legal_domain=LegalDomain.JUVENILE_CHILD_WELFARE,
        authority_family=AuthorityFamily.STATUTE,
        source_name="Wisconsin Statutes Chapter 48 (The Children's Code)",
        provider_name="Wisconsin State Legislature",
        official_status=OfficialStatus.OFFICIAL,
        authority_level=AuthorityLevel.PRIMARY_CONTROLLING,
        canonical_url="https://docs.legis.wisconsin.gov/statutes/statutes/48",
        acquisition_method=AcquisitionMethod.BULK_DOWNLOAD,
        acquisition_mode=AcquisitionMode.HTML_DOCUMENT,
        update_cadence=UpdateCadence.CONTINUOUS,
        temporal_version_semantics="current_through_latest_enacted_act",
        effective_date_semantics="act_specific_effective_dates",
        publication_date_semantics="updated_per_enacted_act_bulletin",
        parser_normalizer_id="wi_statute_html_v1",
        citation_syntax=("Wis. Stat. § 48.{sec}", "Wis. Stat. Ann. § 48.{sec}"),
        currentness_capability=CurrentnessCapability.OFFICIAL_BULLETIN,
        historical_version_capability=True,
        provenance_capability=True,
        auth_requirement=AuthRequirement.NONE,
        licensing_terms_notes="Public government work; open legislative data.",
        availability_status=AvailabilityStatus.AVAILABLE,
        implementation_status=ImplementationStatus.VERIFIED,
        coverage_status=CoverageStatus.VERIFIED,
        last_verified_date=date(2026, 9, 1),
        verification_evidence="Direct inspection of docs.legis.wisconsin.gov/statutes/statutes/48.",
        known_limitations=(
            "Cross-references to federal IV-E or tribal compacts require separate lookup.",
            "Emergency interim legislation published via separate act slips before codification.",
        ),
    ),
    SourceDefinition(
        source_id="US-WI-STATUTES-GENERAL",
        jurisdiction="US-WI",
        geographic_scope=GeographicScope.STATEWIDE,
        legal_domain=LegalDomain.CIVIL_PROCEDURE,
        authority_family=AuthorityFamily.STATUTE,
        source_name="Wisconsin Statutes Chapters 801-847, 901-911, 938",
        provider_name="Wisconsin State Legislature",
        official_status=OfficialStatus.OFFICIAL,
        authority_level=AuthorityLevel.PRIMARY_CONTROLLING,
        canonical_url="https://docs.legis.wisconsin.gov/statutes",
        acquisition_method=AcquisitionMethod.BULK_DOWNLOAD,
        acquisition_mode=AcquisitionMode.HTML_DOCUMENT,
        update_cadence=UpdateCadence.CONTINUOUS,
        temporal_version_semantics="current_through_latest_enacted_act",
        effective_date_semantics="act_specific_effective_dates",
        publication_date_semantics="updated_per_enacted_act_bulletin",
        parser_normalizer_id="wi_statute_html_v1",
        citation_syntax=("Wis. Stat. § {ch}.{sec}",),
        currentness_capability=CurrentnessCapability.OFFICIAL_BULLETIN,
        historical_version_capability=True,
        provenance_capability=True,
        auth_requirement=AuthRequirement.NONE,
        licensing_terms_notes="Public government work.",
        availability_status=AvailabilityStatus.AVAILABLE,
        implementation_status=ImplementationStatus.VERIFIED,
        coverage_status=CoverageStatus.VERIFIED,
        last_verified_date=date(2026, 9, 1),
        verification_evidence="Direct inspection of docs.legis.wisconsin.gov/statutes.",
        known_limitations=("Chapter 938 juvenile justice rules differ materially from Chapter 48 civil CHIPS rules.",),
    ),
    SourceDefinition(
        source_id="US-WI-ADMIN-DCF",
        jurisdiction="US-WI",
        geographic_scope=GeographicScope.STATEWIDE,
        legal_domain=LegalDomain.ADMINISTRATIVE,
        authority_family=AuthorityFamily.ADMINISTRATIVE_CODE,
        source_name="Wisconsin Administrative Code - Department of Children and Families (DCF)",
        provider_name="Wisconsin Legislative Reference Bureau",
        official_status=OfficialStatus.OFFICIAL,
        authority_level=AuthorityLevel.PRIMARY_CONTROLLING,
        canonical_url="https://docs.legis.wisconsin.gov/code/admin_code/dcf",
        acquisition_method=AcquisitionMethod.WEB_FETCH,
        acquisition_mode=AcquisitionMode.HTML_DOCUMENT,
        update_cadence=UpdateCadence.MONTHLY,
        temporal_version_semantics="monthly_administrative_register_updates",
        effective_date_semantics="first_day_of_month_following_publication_unless_specified",
        publication_date_semantics="published_in_wisconsin_administrative_register",
        parser_normalizer_id="wi_admin_code_v1",
        citation_syntax=("Wis. Admin. Code DCF § {sec}",),
        currentness_capability=CurrentnessCapability.OFFICIAL_BULLETIN,
        historical_version_capability=True,
        provenance_capability=True,
        auth_requirement=AuthRequirement.NONE,
        licensing_terms_notes="Public administrative law.",
        availability_status=AvailabilityStatus.AVAILABLE,
        implementation_status=ImplementationStatus.IMPLEMENTED,
        coverage_status=CoverageStatus.BASIC,
        last_verified_date=date(2026, 9, 1),
        verification_evidence="Inspection of docs.legis.wisconsin.gov/code/admin_code/dcf.",
        known_limitations=("Emergency rules expire after 150 days unless extended by JCRAR.",),
    ),
    SourceDefinition(
        source_id="US-WI-COURT-RULES-SCR",
        jurisdiction="US-WI",
        geographic_scope=GeographicScope.STATEWIDE,
        legal_domain=LegalDomain.APPELLATE_PROCEDURE,
        authority_family=AuthorityFamily.COURT_RULES,
        source_name="Wisconsin Supreme Court Rules and Appellate Procedure",
        provider_name="Wisconsin Court System",
        official_status=OfficialStatus.OFFICIAL,
        authority_level=AuthorityLevel.PRIMARY_CONTROLLING,
        canonical_url="https://www.wicourts.gov/scrules/index.htm",
        acquisition_method=AcquisitionMethod.WEB_FETCH,
        acquisition_mode=AcquisitionMode.HTML_DOCUMENT,
        update_cadence=UpdateCadence.IRREGULAR,
        temporal_version_semantics="order_date_and_effective_date_stamped",
        effective_date_semantics="date_fixed_by_supreme_court_order",
        publication_date_semantics="filed_with_supreme_court_clerk",
        parser_normalizer_id="wi_scr_v1",
        citation_syntax=("SCR {rule}", "Wis. Stat. § 809.{sec}"),
        currentness_capability=CurrentnessCapability.LIVE_FEED,
        historical_version_capability=True,
        provenance_capability=True,
        auth_requirement=AuthRequirement.NONE,
        licensing_terms_notes="Official judicial branch publication.",
        availability_status=AvailabilityStatus.AVAILABLE,
        implementation_status=ImplementationStatus.VERIFIED,
        coverage_status=CoverageStatus.BASIC,
        last_verified_date=date(2026, 9, 8),
        verification_evidence="Verified live HTTP 200 via wicourts.gov/scrules/index.htm on 2026-09-08.",
        known_limitations=("Local circuit court rules (e.g. Milwaukee, Dane) are hosted on county-specific subpages.",),
    ),
    SourceDefinition(
        source_id="US-WI-COURTS-CURRENT",
        jurisdiction="US-WI",
        geographic_scope=GeographicScope.STATEWIDE,
        legal_domain=LegalDomain.GENERAL,
        authority_family=AuthorityFamily.JUDICIAL_OPINION,
        source_name="Wisconsin Supreme Court & Court of Appeals Recent Opinions",
        provider_name="Wisconsin Court System",
        official_status=OfficialStatus.OFFICIAL,
        authority_level=AuthorityLevel.PRIMARY_CONTROLLING,
        canonical_url="https://www.wicourts.gov/opinions/index.htm",
        acquisition_method=AcquisitionMethod.WEB_FETCH,
        acquisition_mode=AcquisitionMode.HTML_DOCUMENT,
        update_cadence=UpdateCadence.DAILY,
        temporal_version_semantics="slip_opinions_released_prior_to_reporter_pagination",
        effective_date_semantics="decision_date",
        publication_date_semantics="release_date_and_mandate_date",
        parser_normalizer_id="wi_opinions_slip_v1",
        citation_syntax=("{year} WI {num}", "{year} WI App {num}", "{vol} Wis. 2d {page}", "{vol} N.W.2d {page}"),
        currentness_capability=CurrentnessCapability.LIVE_FEED,
        historical_version_capability=False,
        provenance_capability=True,
        auth_requirement=AuthRequirement.NONE,
        licensing_terms_notes="Public official opinions.",
        availability_status=AvailabilityStatus.AVAILABLE,
        implementation_status=ImplementationStatus.IMPLEMENTED,
        coverage_status=CoverageStatus.BASIC,
        last_verified_date=date(2026, 9, 8),
        verification_evidence="Verified live HTTP 200 via wicourts.gov/opinions/index.htm on 2026-09-08.",
        known_limitations=(
            "Only retains recent opinions on active slip feed; historical search requires archive.",
            "Unpublished opinions under Wis. Stat. § 809.23 cannot be cited as precedent except under specific statutory exceptions.",
        ),
    ),
    SourceDefinition(
        source_id="US-WI-COURTLISTENER-HISTORICAL",
        jurisdiction="US-WI",
        geographic_scope=GeographicScope.STATEWIDE,
        legal_domain=LegalDomain.GENERAL,
        authority_family=AuthorityFamily.JUDICIAL_OPINION,
        source_name="Wisconsin Opinions Historical Corpus (CourtListener Mirror)",
        provider_name="Free Law Project / CourtListener",
        official_status=OfficialStatus.UNOFFICIAL,
        authority_level=AuthorityLevel.PRIMARY_CONTROLLING,
        canonical_url="https://www.courtlistener.com/api/rest/v4/opinions/?court=wis,wisctapp",
        acquisition_method=AcquisitionMethod.REST_API,
        acquisition_mode=AcquisitionMode.JSON_API,
        update_cadence=UpdateCadence.MONTHLY,
        temporal_version_semantics="historical_snapshot_indexed_to_bulk_release",
        effective_date_semantics="date_filed_in_opinion_record",
        publication_date_semantics="courtlistener_ingest_date",
        parser_normalizer_id="courtlistener_opinion_v1",
        citation_syntax=("{vol} Wis. 2d {page}", "{vol} N.W.2d {page}", "{year} WI {num}"),
        currentness_capability=CurrentnessCapability.SNAPSHOT_ONLY,
        historical_version_capability=True,
        provenance_capability=True,
        auth_requirement=AuthRequirement.REQUIRED_KEY,
        licensing_terms_notes="Open database / CC-BY where applicable; third-party provider snapshot.",
        availability_status=AvailabilityStatus.AVAILABLE,
        implementation_status=ImplementationStatus.IMPLEMENTED,
        coverage_status=CoverageStatus.BASIC,
        last_verified_date=date(2026, 9, 8),
        verification_evidence="Direct API response from CourtListener wis/wisctapp endpoints; verified HTTP 401 without API key token on 2026-09-08.",
        known_limitations=(
            "Historical snapshot only; cannot verify live currentness or negative treatment today.",
            "CourtListener v4 REST API requires API key token in Authorization header; unauthenticated requests receive HTTP 401.",
            "May contain OCR artifacts or pagination discrepancies in older pre-1978 opinions.",
        ),
    ),
    SourceDefinition(
        source_id="US-WI-FORMS-JUVENILE",
        jurisdiction="US-WI",
        geographic_scope=GeographicScope.STATEWIDE,
        legal_domain=LegalDomain.JUVENILE_CHILD_WELFARE,
        authority_family=AuthorityFamily.FORMS_GUIDANCE,
        source_name="Wisconsin Juvenile Court Standard Forms (JC-1600 Series)",
        provider_name="Wisconsin Court Records Management Committee",
        official_status=OfficialStatus.OFFICIAL,
        authority_level=AuthorityLevel.PROCESS,
        canonical_url="https://www.wicourts.gov/forms1/circuit/ccform.jsp?Category=26",
        acquisition_method=AcquisitionMethod.WEB_FETCH,
        acquisition_mode=AcquisitionMode.PDF_DOWNLOAD,
        update_cadence=UpdateCadence.ANNUAL,
        temporal_version_semantics="revision_date_on_form",
        effective_date_semantics="form_adoption_order",
        publication_date_semantics="form_release_date",
        parser_normalizer_id="wi_jc_forms_v1",
        citation_syntax=("Wis. Court Form JC-{num}",),
        currentness_capability=CurrentnessCapability.OFFICIAL_BULLETIN,
        historical_version_capability=False,
        provenance_capability=True,
        auth_requirement=AuthRequirement.NONE,
        licensing_terms_notes="Official state court forms.",
        availability_status=AvailabilityStatus.AVAILABLE,
        implementation_status=ImplementationStatus.IMPLEMENTED,
        coverage_status=CoverageStatus.BASIC,
        last_verified_date=date(2026, 9, 1),
        verification_evidence="Inspection of wicourts.gov juvenile forms repository.",
        known_limitations=("Standard forms reflect statutory defaults; local practices and court orders govern specific cases.",),
    ),
    SourceDefinition(
        source_id="US-WI-DCF-SAFETY-STANDARDS",
        jurisdiction="US-WI",
        geographic_scope=GeographicScope.STATEWIDE,
        legal_domain=LegalDomain.JUVENILE_CHILD_WELFARE,
        authority_family=AuthorityFamily.FORMS_GUIDANCE,
        source_name="Wisconsin Child Protective Services Access and Initial Assessment Standards",
        provider_name="Wisconsin Department of Children and Families",
        official_status=OfficialStatus.OFFICIAL,
        authority_level=AuthorityLevel.EXPLANATORY,
        canonical_url="https://dcf.wisconsin.gov/cwportal/policy",
        acquisition_method=AcquisitionMethod.WEB_FETCH,
        acquisition_mode=AcquisitionMode.PDF_DOWNLOAD,
        update_cadence=UpdateCadence.BIENNIAL,
        temporal_version_semantics="policy_memo_effective_date",
        effective_date_semantics="policy_issuance_date",
        publication_date_semantics="cwportal_publication_date",
        parser_normalizer_id="wi_dcf_manual_v1",
        citation_syntax=("Wis. DCF Child Welfare Safety Intervention Standards § {sec}",),
        currentness_capability=CurrentnessCapability.OFFICIAL_BULLETIN,
        historical_version_capability=True,
        provenance_capability=True,
        auth_requirement=AuthRequirement.NONE,
        licensing_terms_notes="State agency guidance manual.",
        availability_status=AvailabilityStatus.AVAILABLE,
        implementation_status=ImplementationStatus.IMPLEMENTED,
        coverage_status=CoverageStatus.BASIC,
        last_verified_date=date(2026, 9, 1),
        verification_evidence="Inspection of dcf.wisconsin.gov policy repository.",
        known_limitations=(
            "Internal agency policy manual; persuasive or explanatory evidence of agency procedure, "
            "not statutory controlling authority in juvenile court.",
        ),
    ),
)


MINNESOTA_SOURCES: tuple[SourceDefinition, ...] = (
    SourceDefinition(
        source_id="US-MN-CONST",
        jurisdiction="US-MN",
        geographic_scope=GeographicScope.STATEWIDE,
        legal_domain=LegalDomain.CONSTITUTIONAL,
        authority_family=AuthorityFamily.CONSTITUTION,
        source_name="Minnesota Constitution",
        provider_name="Minnesota Office of the Revisor of Statutes",
        official_status=OfficialStatus.OFFICIAL,
        authority_level=AuthorityLevel.PRIMARY_CONTROLLING,
        canonical_url="https://www.revisor.mn.gov/constitution/",
        acquisition_method=AcquisitionMethod.WEB_FETCH,
        acquisition_mode=AcquisitionMode.HTML_DOCUMENT,
        update_cadence=UpdateCadence.SESSIONAL,
        temporal_version_semantics="current_in_force_with_historical_notes",
        effective_date_semantics="constitutional_amendment_effective_date",
        publication_date_semantics="revisor_compilation_date",
        parser_normalizer_id="mn_revisor_html_v1",
        citation_syntax=("Minn. Const. art. {art}, § {sec}",),
        currentness_capability=CurrentnessCapability.OFFICIAL_BULLETIN,
        historical_version_capability=True,
        provenance_capability=True,
        auth_requirement=AuthRequirement.NONE,
        licensing_terms_notes="Public statutory repository; Minnesota Revisor public domain.",
        availability_status=AvailabilityStatus.AVAILABLE,
        implementation_status=ImplementationStatus.VERIFIED,
        coverage_status=CoverageStatus.VERIFIED,
        last_verified_date=date(2026, 9, 1),
        verification_evidence="Direct inspection of revisor.mn.gov/constitution/.",
        known_limitations=("Does not provide direct git or API diffing; point-in-time lookup available via archive.",),
    ),
    SourceDefinition(
        source_id="US-MN-STATUTES-CH260C",
        jurisdiction="US-MN",
        geographic_scope=GeographicScope.STATEWIDE,
        legal_domain=LegalDomain.JUVENILE_CHILD_WELFARE,
        authority_family=AuthorityFamily.STATUTE,
        source_name="Minnesota Statutes Chapter 260C (Juvenile Safety and Placement)",
        provider_name="Minnesota Office of the Revisor of Statutes",
        official_status=OfficialStatus.OFFICIAL,
        authority_level=AuthorityLevel.PRIMARY_CONTROLLING,
        canonical_url="https://www.revisor.mn.gov/statutes/cite/260C",
        acquisition_method=AcquisitionMethod.BULK_DOWNLOAD,
        acquisition_mode=AcquisitionMode.XML_FEED,
        update_cadence=UpdateCadence.CONTINUOUS,
        temporal_version_semantics="current_through_latest_session_laws",
        effective_date_semantics="effective_per_session_law_provisions",
        publication_date_semantics="revisor_codification_release",
        parser_normalizer_id="mn_revisor_xml_v1",
        citation_syntax=("Minn. Stat. § 260C.{sec}", "Minn. Stat. Ann. § 260C.{sec}"),
        currentness_capability=CurrentnessCapability.OFFICIAL_BULLETIN,
        historical_version_capability=True,
        provenance_capability=True,
        auth_requirement=AuthRequirement.NONE,
        licensing_terms_notes="Official Minnesota Revisor data.",
        availability_status=AvailabilityStatus.AVAILABLE,
        implementation_status=ImplementationStatus.VERIFIED,
        coverage_status=CoverageStatus.VERIFIED,
        last_verified_date=date(2026, 9, 1),
        verification_evidence="Inspection of revisor.mn.gov XML bulk downloads and statute pages.",
        known_limitations=(
            "Session laws take effect August 1 unless otherwise specified or vetoed.",
            "Substantive definitions interact with chapter 260 (general) and chapter 260D (voluntary foster care).",
        ),
    ),
    SourceDefinition(
        source_id="US-MN-STATUTES-GENERAL",
        jurisdiction="US-MN",
        geographic_scope=GeographicScope.STATEWIDE,
        legal_domain=LegalDomain.CIVIL_PROCEDURE,
        authority_family=AuthorityFamily.STATUTE,
        source_name="Minnesota Statutes Chapters 256, 259, 260, 260D",
        provider_name="Minnesota Office of the Revisor of Statutes",
        official_status=OfficialStatus.OFFICIAL,
        authority_level=AuthorityLevel.PRIMARY_CONTROLLING,
        canonical_url="https://www.revisor.mn.gov/statutes/",
        acquisition_method=AcquisitionMethod.BULK_DOWNLOAD,
        acquisition_mode=AcquisitionMode.XML_FEED,
        update_cadence=UpdateCadence.CONTINUOUS,
        temporal_version_semantics="current_through_latest_session_laws",
        effective_date_semantics="effective_per_session_law_provisions",
        publication_date_semantics="revisor_codification_release",
        parser_normalizer_id="mn_revisor_xml_v1",
        citation_syntax=("Minn. Stat. § {ch}.{sec}",),
        currentness_capability=CurrentnessCapability.OFFICIAL_BULLETIN,
        historical_version_capability=True,
        provenance_capability=True,
        auth_requirement=AuthRequirement.NONE,
        licensing_terms_notes="Official Minnesota Revisor data.",
        availability_status=AvailabilityStatus.AVAILABLE,
        implementation_status=ImplementationStatus.VERIFIED,
        coverage_status=CoverageStatus.VERIFIED,
        last_verified_date=date(2026, 9, 1),
        verification_evidence="Inspection of revisor.mn.gov/statutes/.",
        known_limitations=("Northstar Care for Children (ch. 256N) modifies relative placement and subsidy rules.",),
    ),
    SourceDefinition(
        source_id="US-MN-MRJPP",
        jurisdiction="US-MN",
        geographic_scope=GeographicScope.STATEWIDE,
        legal_domain=LegalDomain.JUVENILE_CHILD_WELFARE,
        authority_family=AuthorityFamily.COURT_RULES,
        source_name="Minnesota Rules of Juvenile Protection Procedure",
        provider_name="Minnesota Judicial Branch / Revisor",
        official_status=OfficialStatus.OFFICIAL,
        authority_level=AuthorityLevel.PRIMARY_CONTROLLING,
        canonical_url="https://www.revisor.mn.gov/court_rules/rule/jurjpp-toh/",
        acquisition_method=AcquisitionMethod.WEB_FETCH,
        acquisition_mode=AcquisitionMode.HTML_DOCUMENT,
        update_cadence=UpdateCadence.IRREGULAR,
        temporal_version_semantics="supreme_court_order_effective_date",
        effective_date_semantics="promulgated_by_supreme_court_order",
        publication_date_semantics="filed_in_appellate_courts_clerk_office",
        parser_normalizer_id="mn_mrjpp_v1",
        citation_syntax=("Minn. R. Juv. Prot. P. {rule}", "MRJPP Rule {rule}"),
        currentness_capability=CurrentnessCapability.OFFICIAL_BULLETIN,
        historical_version_capability=True,
        provenance_capability=True,
        auth_requirement=AuthRequirement.NONE,
        licensing_terms_notes="Public official court rules.",
        availability_status=AvailabilityStatus.AVAILABLE,
        implementation_status=ImplementationStatus.VERIFIED,
        coverage_status=CoverageStatus.VERIFIED,
        last_verified_date=date(2026, 9, 8),
        verification_evidence="Verified live HTTP 200 via revisor.mn.gov/court_rules/rule/jurjpp-toh/ on 2026-09-08.",
        known_limitations=(
            "Rules govern over conflicting civil procedure rules in juvenile protection proceedings, "
            "per MRJPP Rule 3.",
        ),
    ),
    SourceDefinition(
        source_id="US-MN-EVIDENCE-APPELLATE-RULES",
        jurisdiction="US-MN",
        geographic_scope=GeographicScope.STATEWIDE,
        legal_domain=LegalDomain.APPELLATE_PROCEDURE,
        authority_family=AuthorityFamily.COURT_RULES,
        source_name="Minnesota Rules of Evidence (MRE) and Civil Appellate Procedure (RCAP)",
        provider_name="Minnesota Judicial Branch / Revisor",
        official_status=OfficialStatus.OFFICIAL,
        authority_level=AuthorityLevel.PRIMARY_CONTROLLING,
        canonical_url="https://www.revisor.mn.gov/court_rules/",
        acquisition_method=AcquisitionMethod.WEB_FETCH,
        acquisition_mode=AcquisitionMode.HTML_DOCUMENT,
        update_cadence=UpdateCadence.IRREGULAR,
        temporal_version_semantics="supreme_court_order_effective_date",
        effective_date_semantics="promulgated_by_supreme_court_order",
        publication_date_semantics="filed_with_appellate_courts_clerk",
        parser_normalizer_id="mn_court_rules_v1",
        citation_syntax=("Minn. R. Evid. {rule}", "Minn. R. Civ. App. P. {rule}"),
        currentness_capability=CurrentnessCapability.OFFICIAL_BULLETIN,
        historical_version_capability=True,
        provenance_capability=True,
        auth_requirement=AuthRequirement.NONE,
        licensing_terms_notes="Public official court rules.",
        availability_status=AvailabilityStatus.AVAILABLE,
        implementation_status=ImplementationStatus.VERIFIED,
        coverage_status=CoverageStatus.BASIC,
        last_verified_date=date(2026, 9, 8),
        verification_evidence="Verified live HTTP 200 via revisor.mn.gov/court_rules/ on 2026-09-08.",
        known_limitations=("Juvenile protection appeals have shortened 20-day notice requirement under MRJPP / RCAP.",),
    ),
    SourceDefinition(
        source_id="US-MN-ADMIN-RULES-DHS",
        jurisdiction="US-MN",
        geographic_scope=GeographicScope.STATEWIDE,
        legal_domain=LegalDomain.ADMINISTRATIVE,
        authority_family=AuthorityFamily.ADMINISTRATIVE_CODE,
        source_name="Minnesota Administrative Rules Chapter 9560 (DHS Child Welfare)",
        provider_name="Minnesota Department of Human Services / Revisor",
        official_status=OfficialStatus.OFFICIAL,
        authority_level=AuthorityLevel.PRIMARY_CONTROLLING,
        canonical_url="https://www.revisor.mn.gov/rules/9560/",
        acquisition_method=AcquisitionMethod.WEB_FETCH,
        acquisition_mode=AcquisitionMode.HTML_DOCUMENT,
        update_cadence=UpdateCadence.MONTHLY,
        temporal_version_semantics="published_in_state_register",
        effective_date_semantics="effective_five_working_days_after_publication",
        publication_date_semantics="revisor_compilation_date",
        parser_normalizer_id="mn_admin_rules_v1",
        citation_syntax=("Minn. R. 9560.{sec}",),
        currentness_capability=CurrentnessCapability.OFFICIAL_BULLETIN,
        historical_version_capability=True,
        provenance_capability=True,
        auth_requirement=AuthRequirement.NONE,
        licensing_terms_notes="Public administrative rules.",
        availability_status=AvailabilityStatus.AVAILABLE,
        implementation_status=ImplementationStatus.IMPLEMENTED,
        coverage_status=CoverageStatus.BASIC,
        last_verified_date=date(2026, 9, 8),
        verification_evidence="Verified live HTTP 200 via revisor.mn.gov/rules/9560/ on 2026-09-08.",
        known_limitations=("Covers foster care licensure, kinship assessment, and state adoption assistance.",),
    ),
    SourceDefinition(
        source_id="US-MN-COURTS-CURRENT",
        jurisdiction="US-MN",
        geographic_scope=GeographicScope.STATEWIDE,
        legal_domain=LegalDomain.GENERAL,
        authority_family=AuthorityFamily.JUDICIAL_OPINION,
        source_name="Minnesota Supreme Court & Court of Appeals Recent Opinions",
        provider_name="Minnesota Judicial Branch",
        official_status=OfficialStatus.OFFICIAL,
        authority_level=AuthorityLevel.PRIMARY_CONTROLLING,
        canonical_url="https://mncourts.gov/SupremeCourt/Recent-Opinions.aspx",
        acquisition_method=AcquisitionMethod.WEB_FETCH,
        acquisition_mode=AcquisitionMode.RSS_FEED,
        update_cadence=UpdateCadence.WEEKLY,
        temporal_version_semantics="released_every_monday_or_wednesday_slip_opinions",
        effective_date_semantics="filing_date_with_clerk_of_appellate_courts",
        publication_date_semantics="official_release_date",
        parser_normalizer_id="mn_opinions_slip_v1",
        citation_syntax=("{vol} N.W.2d {page}", "{case_no} (Minn. {year})", "{case_no} (Minn. Ct. App. {year})"),
        currentness_capability=CurrentnessCapability.LIVE_FEED,
        historical_version_capability=False,
        provenance_capability=True,
        auth_requirement=AuthRequirement.NONE,
        licensing_terms_notes="Official Minnesota judicial branch releases.",
        availability_status=AvailabilityStatus.RESTRICTED,
        implementation_status=ImplementationStatus.IMPLEMENTED,
        coverage_status=CoverageStatus.BASIC,
        last_verified_date=date(2026, 9, 8),
        verification_evidence="Inspected mncourts.gov/SupremeCourt/Recent-Opinions.aspx on 2026-09-08; portal verified active behind WAF challenge.",
        known_limitations=(
            "Web portal employs WAF bot-challenge blocking automated script curl/urllib (HTTP 403); automated ingest requires browser session or authenticated feed.",
            "Slip opinions are published without North Western Reporter page numbers.",
            "Nonprecedential opinions under Minn. Stat. § 480A.08, subd. 3 must be distinguished from precedential.",
        ),
    ),
    SourceDefinition(
        source_id="US-MN-COURTLISTENER-HISTORICAL",
        jurisdiction="US-MN",
        geographic_scope=GeographicScope.STATEWIDE,
        legal_domain=LegalDomain.GENERAL,
        authority_family=AuthorityFamily.JUDICIAL_OPINION,
        source_name="Minnesota Opinions Historical Corpus (CourtListener Mirror)",
        provider_name="Free Law Project / CourtListener",
        official_status=OfficialStatus.UNOFFICIAL,
        authority_level=AuthorityLevel.PRIMARY_CONTROLLING,
        canonical_url="https://www.courtlistener.com/api/rest/v4/opinions/?court=minn,minnctapp",
        acquisition_method=AcquisitionMethod.REST_API,
        acquisition_mode=AcquisitionMode.JSON_API,
        update_cadence=UpdateCadence.MONTHLY,
        temporal_version_semantics="historical_snapshot_indexed_to_bulk_release",
        effective_date_semantics="date_filed_in_opinion_record",
        publication_date_semantics="courtlistener_ingest_date",
        parser_normalizer_id="courtlistener_opinion_v1",
        citation_syntax=("{vol} N.W.2d {page}", "{vol} Minn. {page}"),
        currentness_capability=CurrentnessCapability.SNAPSHOT_ONLY,
        historical_version_capability=True,
        provenance_capability=True,
        auth_requirement=AuthRequirement.REQUIRED_KEY,
        licensing_terms_notes="Open database / CC-BY where applicable.",
        availability_status=AvailabilityStatus.AVAILABLE,
        implementation_status=ImplementationStatus.IMPLEMENTED,
        coverage_status=CoverageStatus.BASIC,
        last_verified_date=date(2026, 9, 8),
        verification_evidence="Direct API response from CourtListener minn/minnctapp endpoints; verified HTTP 401 without API key token on 2026-09-08.",
        known_limitations=(
            "Historical snapshot only; cannot verify live currentness or negative treatment today.",
            "CourtListener v4 REST API requires API key token in Authorization header; unauthenticated requests receive HTTP 401.",
            "Precedential vs nonprecedential status tagging requires verification against Minnesota Court of Appeals orders.",
        ),
    ),
    SourceDefinition(
        source_id="US-MN-FORMS-JUVENILE",
        jurisdiction="US-MN",
        geographic_scope=GeographicScope.STATEWIDE,
        legal_domain=LegalDomain.JUVENILE_CHILD_WELFARE,
        authority_family=AuthorityFamily.FORMS_GUIDANCE,
        source_name="Minnesota Judicial Branch Child Protection Court Forms",
        provider_name="Minnesota State Court Administrator's Office",
        official_status=OfficialStatus.OFFICIAL,
        authority_level=AuthorityLevel.PROCESS,
        canonical_url="https://mncourts.gov/GetForms.aspx?c=7",
        acquisition_method=AcquisitionMethod.WEB_FETCH,
        acquisition_mode=AcquisitionMode.PDF_DOWNLOAD,
        update_cadence=UpdateCadence.ANNUAL,
        temporal_version_semantics="form_revision_date",
        effective_date_semantics="state_court_administrator_adoption",
        publication_date_semantics="mncourts_publication_date",
        parser_normalizer_id="mn_court_forms_v1",
        citation_syntax=("Minn. Court Form CHP{num}",),
        currentness_capability=CurrentnessCapability.OFFICIAL_BULLETIN,
        historical_version_capability=False,
        provenance_capability=True,
        auth_requirement=AuthRequirement.NONE,
        licensing_terms_notes="Official court forms.",
        availability_status=AvailabilityStatus.RESTRICTED,
        implementation_status=ImplementationStatus.IMPLEMENTED,
        coverage_status=CoverageStatus.BASIC,
        last_verified_date=date(2026, 9, 8),
        verification_evidence="Inspected mncourts.gov/GetForms.aspx?c=7 on 2026-09-08; portal verified active behind WAF challenge.",
        known_limitations=(
            "Portal employs WAF bot-challenge blocking automated script fetch (HTTP 403); automated ingest requires browser session.",
            "Standard forms provide procedural structure; local county standing orders may add requirements.",
        ),
    ),
    SourceDefinition(
        source_id="US-MN-DHS-CHILD-SAFETY-MANUAL",
        jurisdiction="US-MN",
        geographic_scope=GeographicScope.STATEWIDE,
        legal_domain=LegalDomain.JUVENILE_CHILD_WELFARE,
        authority_family=AuthorityFamily.FORMS_GUIDANCE,
        source_name="Minnesota Child Safety and Permanency Policy Manual",
        provider_name="Minnesota Department of Human Services",
        official_status=OfficialStatus.OFFICIAL,
        authority_level=AuthorityLevel.EXPLANATORY,
        canonical_url="https://mn.gov/dhs/partners-and-providers/policies-procedures/child-welfare/",
        acquisition_method=AcquisitionMethod.WEB_FETCH,
        acquisition_mode=AcquisitionMode.PDF_DOWNLOAD,
        update_cadence=UpdateCadence.BIENNIAL,
        temporal_version_semantics="bulletin_issuance_and_manual_revision",
        effective_date_semantics="dhs_bulletin_effective_date",
        publication_date_semantics="dhs_web_posting_date",
        parser_normalizer_id="mn_dhs_manual_v1",
        citation_syntax=("Minn. DHS Child Welfare Manual § {sec}",),
        currentness_capability=CurrentnessCapability.OFFICIAL_BULLETIN,
        historical_version_capability=True,
        provenance_capability=True,
        auth_requirement=AuthRequirement.NONE,
        licensing_terms_notes="State agency guidance.",
        availability_status=AvailabilityStatus.AVAILABLE,
        implementation_status=ImplementationStatus.IMPLEMENTED,
        coverage_status=CoverageStatus.BASIC,
        last_verified_date=date(2026, 9, 1),
        verification_evidence="Inspection of mn.gov/dhs child welfare policy site.",
        known_limitations=("Department guidance to county social services; not binding on juvenile court judges.",),
    ),
)


FEDERAL_OVERLAY_SOURCES: tuple[SourceDefinition, ...] = (
    SourceDefinition(
        source_id="US-FED-CONST",
        jurisdiction="US",
        geographic_scope=GeographicScope.NATIONAL,
        legal_domain=LegalDomain.CONSTITUTIONAL,
        authority_family=AuthorityFamily.CONSTITUTION,
        source_name="United States Constitution",
        provider_name="Library of Congress / National Archives",
        official_status=OfficialStatus.OFFICIAL,
        authority_level=AuthorityLevel.PRIMARY_CONTROLLING,
        canonical_url="https://www.govinfo.gov/app/collection/constitution",
        acquisition_method=AcquisitionMethod.WEB_FETCH,
        acquisition_mode=AcquisitionMode.HTML_DOCUMENT,
        update_cadence=UpdateCadence.IRREGULAR,
        temporal_version_semantics="current_in_force_with_amendment_ratification_dates",
        effective_date_semantics="ratification_by_three_fourths_of_states",
        publication_date_semantics="gpo_constitution_annotated_edition",
        parser_normalizer_id="us_const_annotated_v1",
        citation_syntax=("U.S. Const. amend. {num}", "U.S. Const. art. {art}, § {sec}"),
        currentness_capability=CurrentnessCapability.OFFICIAL_BULLETIN,
        historical_version_capability=True,
        provenance_capability=True,
        auth_requirement=AuthRequirement.NONE,
        licensing_terms_notes="United States Government Work - 17 U.S.C. § 105.",
        availability_status=AvailabilityStatus.AVAILABLE,
        implementation_status=ImplementationStatus.VERIFIED,
        coverage_status=CoverageStatus.VERIFIED,
        last_verified_date=date(2026, 9, 8),
        verification_evidence="Verified live HTTP 200 via govinfo.gov/app/collection/constitution on 2026-09-08; secondary mirror verified at archives.gov/founding-docs/constitution.",
        known_limitations=(
            "Official authenticated digital compilation provided by GPO GovInfo; Library of Congress constitution.congress.gov employs WAF bot-protection.",
            "Constitution Annotated provides scholarly analysis alongside text.",
        ),
    ),
    SourceDefinition(
        source_id="US-FED-USC-CIVIL-RIGHTS-CHILD-WELFARE",
        jurisdiction="US",
        geographic_scope=GeographicScope.NATIONAL,
        legal_domain=LegalDomain.CIVIL_RIGHTS,
        authority_family=AuthorityFamily.STATUTE,
        source_name="United States Code (Titles 42, 25, 28)",
        provider_name="Office of the Law Revision Counsel (OLRC)",
        official_status=OfficialStatus.OFFICIAL,
        authority_level=AuthorityLevel.PRIMARY_CONTROLLING,
        canonical_url="https://uscode.house.gov/",
        acquisition_method=AcquisitionMethod.BULK_DOWNLOAD,
        acquisition_mode=AcquisitionMode.XML_FEED,
        update_cadence=UpdateCadence.CONTINUOUS,
        temporal_version_semantics="public_law_currency_stamped_by_olrc",
        effective_date_semantics="statutory_effective_date_or_enactment",
        publication_date_semantics="olrc_codification_release",
        parser_normalizer_id="uscode_olrc_xml_v1",
        citation_syntax=("{title} U.S.C. § {sec}",),
        currentness_capability=CurrentnessCapability.OFFICIAL_BULLETIN,
        historical_version_capability=True,
        provenance_capability=True,
        auth_requirement=AuthRequirement.NONE,
        licensing_terms_notes="United States Government Work - 17 U.S.C. § 105.",
        availability_status=AvailabilityStatus.AVAILABLE,
        implementation_status=ImplementationStatus.VERIFIED,
        coverage_status=CoverageStatus.VERIFIED,
        last_verified_date=date(2026, 9, 1),
        verification_evidence="Direct inspection of uscode.house.gov and GovInfo USCODE collection.",
        known_limitations=(
            "OLRC codification lags public law enactment by several weeks to months during active sessions.",
            "Positive law titles have prima facie vs positive legal status nuances.",
        ),
    ),
    SourceDefinition(
        source_id="US-FED-CFR-CHILD-WELFARE",
        jurisdiction="US",
        geographic_scope=GeographicScope.NATIONAL,
        legal_domain=LegalDomain.ADMINISTRATIVE,
        authority_family=AuthorityFamily.ADMINISTRATIVE_CODE,
        source_name="Electronic Code of Federal Regulations (eCFR - 45 CFR Parts 1355-1356, 25 CFR Part 23)",
        provider_name="National Archives and Records Administration (NARA) / GPO",
        official_status=OfficialStatus.OFFICIAL,
        authority_level=AuthorityLevel.PRIMARY_CONTROLLING,
        canonical_url="https://www.ecfr.gov/",
        acquisition_method=AcquisitionMethod.REST_API,
        acquisition_mode=AcquisitionMode.JSON_API,
        update_cadence=UpdateCadence.DAILY,
        temporal_version_semantics="point_in_time_daily_compilation",
        effective_date_semantics="effective_date_specified_in_federal_register_rule",
        publication_date_semantics="nara_daily_update",
        parser_normalizer_id="ecfr_api_v1",
        citation_syntax=("{title} C.F.R. § {sec}",),
        currentness_capability=CurrentnessCapability.LIVE_FEED,
        historical_version_capability=True,
        provenance_capability=True,
        auth_requirement=AuthRequirement.NONE,
        licensing_terms_notes="United States Government Work.",
        availability_status=AvailabilityStatus.AVAILABLE,
        implementation_status=ImplementationStatus.VERIFIED,
        coverage_status=CoverageStatus.VERIFIED,
        last_verified_date=date(2026, 9, 1),
        verification_evidence="Direct inspection of ecfr.gov API documentation.",
        known_limitations=("eCFR is an editorial compilation; annual CFR volumes on GovInfo are official legal evidence.",),
    ),
    SourceDefinition(
        source_id="US-FED-RULES-PROCEDURE",
        jurisdiction="US",
        geographic_scope=GeographicScope.NATIONAL,
        legal_domain=LegalDomain.CIVIL_PROCEDURE,
        authority_family=AuthorityFamily.COURT_RULES,
        source_name="Federal Rules of Civil Procedure, Evidence, and Appellate Procedure",
        provider_name="Administrative Office of the U.S. Courts",
        official_status=OfficialStatus.OFFICIAL,
        authority_level=AuthorityLevel.PRIMARY_CONTROLLING,
        canonical_url="https://www.uscourts.gov/rules-policies/current-rules-practice-procedure",
        acquisition_method=AcquisitionMethod.WEB_FETCH,
        acquisition_mode=AcquisitionMode.PDF_DOWNLOAD,
        update_cadence=UpdateCadence.ANNUAL,
        temporal_version_semantics="effective_december_1_annually_under_rules_enabling_act",
        effective_date_semantics="prescribed_by_supreme_court_order",
        publication_date_semantics="house_judiciary_committee_print",
        parser_normalizer_id="us_court_rules_v1",
        citation_syntax=("Fed. R. Civ. P. {rule}", "Fed. R. Evid. {rule}", "Fed. R. App. P. {rule}"),
        currentness_capability=CurrentnessCapability.OFFICIAL_BULLETIN,
        historical_version_capability=True,
        provenance_capability=True,
        auth_requirement=AuthRequirement.NONE,
        licensing_terms_notes="Public government rules.",
        availability_status=AvailabilityStatus.AVAILABLE,
        implementation_status=ImplementationStatus.VERIFIED,
        coverage_status=CoverageStatus.VERIFIED,
        last_verified_date=date(2026, 9, 1),
        verification_evidence="Inspection of uscourts.gov rules portal.",
        known_limitations=("Local district and circuit rules supplement federal rules under FRCP 83.",),
    ),
    SourceDefinition(
        source_id="US-FED-SCOTUS-OFFICIAL",
        jurisdiction="US",
        geographic_scope=GeographicScope.NATIONAL,
        legal_domain=LegalDomain.GENERAL,
        authority_family=AuthorityFamily.JUDICIAL_OPINION,
        source_name="Supreme Court of the United States Slip Opinions & Bound Volumes",
        provider_name="Supreme Court of the United States",
        official_status=OfficialStatus.OFFICIAL,
        authority_level=AuthorityLevel.PRIMARY_CONTROLLING,
        canonical_url="https://www.supremecourt.gov/opinions/opinions.aspx",
        acquisition_method=AcquisitionMethod.WEB_FETCH,
        acquisition_mode=AcquisitionMode.PDF_DOWNLOAD,
        update_cadence=UpdateCadence.DAILY,
        temporal_version_semantics="bench_opinions_slip_opinions_preliminary_prints_united_states_reports",
        effective_date_semantics="bench_release_date",
        publication_date_semantics="official_us_reports_pagination",
        parser_normalizer_id="scotus_official_pdf_v1",
        citation_syntax=("{vol} U.S. {page}", "{vol} S. Ct. {page}"),
        currentness_capability=CurrentnessCapability.LIVE_FEED,
        historical_version_capability=True,
        provenance_capability=True,
        auth_requirement=AuthRequirement.NONE,
        licensing_terms_notes="United States Government Work.",
        availability_status=AvailabilityStatus.AVAILABLE,
        implementation_status=ImplementationStatus.IMPLEMENTED,
        coverage_status=CoverageStatus.BASIC,
        last_verified_date=date(2026, 9, 1),
        verification_evidence="Inspection of supremecourt.gov/opinions.",
        known_limitations=(
            "Slip opinions subject to formal revision prior to publication in United States Reports.",
            "Bound volume publication runs several years behind bench delivery.",
        ),
    ),
    SourceDefinition(
        source_id="US-FED-CA7-OFFICIAL",
        jurisdiction="US-7th-Cir",
        geographic_scope=GeographicScope.CIRCUIT_7,
        legal_domain=LegalDomain.GENERAL,
        authority_family=AuthorityFamily.JUDICIAL_OPINION,
        source_name="United States Court of Appeals for the Seventh Circuit Opinions",
        provider_name="U.S. Court of Appeals for the Seventh Circuit",
        official_status=OfficialStatus.OFFICIAL,
        authority_level=AuthorityLevel.PRIMARY_CONTROLLING,
        canonical_url="https://media.ca7.uscourts.gov/opinion.html",
        acquisition_method=AcquisitionMethod.WEB_FETCH,
        acquisition_mode=AcquisitionMode.RSS_FEED,
        update_cadence=UpdateCadence.DAILY,
        temporal_version_semantics="daily_opinion_release_feed",
        effective_date_semantics="date_filed",
        publication_date_semantics="release_date",
        parser_normalizer_id="ca7_opinion_v1",
        citation_syntax=("{vol} F.3d {page}", "{vol} F.4th {page}"),
        currentness_capability=CurrentnessCapability.LIVE_FEED,
        historical_version_capability=False,
        provenance_capability=True,
        auth_requirement=AuthRequirement.NONE,
        licensing_terms_notes="Federal court official releases.",
        availability_status=AvailabilityStatus.AVAILABLE,
        implementation_status=ImplementationStatus.IMPLEMENTED,
        coverage_status=CoverageStatus.BASIC,
        last_verified_date=date(2026, 9, 8),
        verification_evidence="Verified live HTTP 200 via media.ca7.uscourts.gov/opinion.html on 2026-09-08.",
        known_limitations=("Circuit Rule 32.1 governs nonprecedential dispositions.",),
    ),
    SourceDefinition(
        source_id="US-FED-CA8-OFFICIAL",
        jurisdiction="US-8th-Cir",
        geographic_scope=GeographicScope.CIRCUIT_8,
        legal_domain=LegalDomain.GENERAL,
        authority_family=AuthorityFamily.JUDICIAL_OPINION,
        source_name="United States Court of Appeals for the Eighth Circuit Opinions",
        provider_name="U.S. Court of Appeals for the Eighth Circuit",
        official_status=OfficialStatus.OFFICIAL,
        authority_level=AuthorityLevel.PRIMARY_CONTROLLING,
        canonical_url="https://www.ca8.uscourts.gov/opinions",
        acquisition_method=AcquisitionMethod.WEB_FETCH,
        acquisition_mode=AcquisitionMode.RSS_FEED,
        update_cadence=UpdateCadence.DAILY,
        temporal_version_semantics="daily_opinion_release_feed",
        effective_date_semantics="date_filed",
        publication_date_semantics="release_date",
        parser_normalizer_id="ca8_opinion_v1",
        citation_syntax=("{vol} F.3d {page}", "{vol} F.4th {page}"),
        currentness_capability=CurrentnessCapability.LIVE_FEED,
        historical_version_capability=False,
        provenance_capability=True,
        auth_requirement=AuthRequirement.NONE,
        licensing_terms_notes="Federal court official releases.",
        availability_status=AvailabilityStatus.AVAILABLE,
        implementation_status=ImplementationStatus.IMPLEMENTED,
        coverage_status=CoverageStatus.BASIC,
        last_verified_date=date(2026, 9, 8),
        verification_evidence="Verified live HTTP 200 via ca8.uscourts.gov/opinions on 2026-09-08.",
        known_limitations=("Unpublished per curiam opinions are not precedential pursuant to 8th Cir. R. 32.1A.",),
    ),
    SourceDefinition(
        source_id="US-FED-GOVINFO",
        jurisdiction="US",
        geographic_scope=GeographicScope.NATIONAL,
        legal_domain=LegalDomain.GENERAL,
        authority_family=AuthorityFamily.STATUTE,
        source_name="GovInfo Authentication and Digital Repository",
        provider_name="U.S. Government Publishing Office (GPO)",
        official_status=OfficialStatus.OFFICIAL,
        authority_level=AuthorityLevel.PRIMARY_CONTROLLING,
        canonical_url="https://api.govinfo.gov/",
        acquisition_method=AcquisitionMethod.REST_API,
        acquisition_mode=AcquisitionMode.JSON_API,
        update_cadence=UpdateCadence.DAILY,
        temporal_version_semantics="digitally_signed_cryptographically_verified_pdf_and_xml",
        effective_date_semantics="per_collection_effective_date",
        publication_date_semantics="gpo_authenticated_publication_date",
        parser_normalizer_id="govinfo_api_v1",
        citation_syntax=("{collection} package {package_id}",),
        currentness_capability=CurrentnessCapability.OFFICIAL_BULLETIN,
        historical_version_capability=True,
        provenance_capability=True,
        auth_requirement=AuthRequirement.REQUIRED_KEY,
        licensing_terms_notes="United States Government Work - 17 U.S.C. § 105.",
        availability_status=AvailabilityStatus.AVAILABLE,
        implementation_status=ImplementationStatus.IMPLEMENTED,
        coverage_status=CoverageStatus.VERIFIED,
        last_verified_date=date(2026, 9, 8),
        verification_evidence="Direct inspection of api.govinfo.gov documentation and collections; HTTP 200 verified on 2026-09-08.",
        known_limitations=("API rate limits apply (1,000 requests/hour default); requires developer API key.",),
    ),
    SourceDefinition(
        source_id="US-FED-CONGRESS-GOV",
        jurisdiction="US",
        geographic_scope=GeographicScope.NATIONAL,
        legal_domain=LegalDomain.CONSTITUTIONAL,
        authority_family=AuthorityFamily.STATUTE,
        source_name="Congress.gov Legislative Tracking and Bill Status API",
        provider_name="Library of Congress",
        official_status=OfficialStatus.OFFICIAL,
        authority_level=AuthorityLevel.PRIMARY_CONTROLLING,
        canonical_url="https://api.congress.gov/",
        acquisition_method=AcquisitionMethod.REST_API,
        acquisition_mode=AcquisitionMode.JSON_API,
        update_cadence=UpdateCadence.DAILY,
        temporal_version_semantics="bill_version_chronology",
        effective_date_semantics="enactment_and_effective_dates_in_text",
        publication_date_semantics="congressional_record_date",
        parser_normalizer_id="congress_gov_api_v1",
        citation_syntax=("Pub. L. {congress}-{num}", "H.R. {num}", "S. {num}"),
        currentness_capability=CurrentnessCapability.LIVE_FEED,
        historical_version_capability=True,
        provenance_capability=True,
        auth_requirement=AuthRequirement.REQUIRED_KEY,
        licensing_terms_notes="Open legislative data provided by Library of Congress.",
        availability_status=AvailabilityStatus.AVAILABLE,
        implementation_status=ImplementationStatus.IMPLEMENTED,
        coverage_status=CoverageStatus.BASIC,
        last_verified_date=date(2026, 9, 8),
        verification_evidence="Inspection of api.congress.gov endpoints; HTTP 200 verified on 2026-09-08.",
        known_limitations=("Bills prior to enactment are non-binding legislative proposals.",),
    ),
    SourceDefinition(
        source_id="US-FED-FEDERAL-REGISTER",
        jurisdiction="US",
        geographic_scope=GeographicScope.NATIONAL,
        legal_domain=LegalDomain.ADMINISTRATIVE,
        authority_family=AuthorityFamily.ADMINISTRATIVE_CODE,
        source_name="Federal Register Daily Journal and API",
        provider_name="National Archives and Records Administration (NARA)",
        official_status=OfficialStatus.OFFICIAL,
        authority_level=AuthorityLevel.PRIMARY_CONTROLLING,
        canonical_url="https://www.federalregister.gov/api/v1/documents.json",
        acquisition_method=AcquisitionMethod.REST_API,
        acquisition_mode=AcquisitionMode.JSON_API,
        update_cadence=UpdateCadence.DAILY,
        temporal_version_semantics="daily_published_issues_since_1994",
        effective_date_semantics="effective_date_in_final_rule_notice",
        publication_date_semantics="daily_issue_publication_date",
        parser_normalizer_id="federal_register_api_v1",
        citation_syntax=("{vol} Fed. Reg. {page}",),
        currentness_capability=CurrentnessCapability.LIVE_FEED,
        historical_version_capability=True,
        provenance_capability=True,
        auth_requirement=AuthRequirement.NONE,
        licensing_terms_notes="United States Government Work.",
        availability_status=AvailabilityStatus.AVAILABLE,
        implementation_status=ImplementationStatus.VERIFIED,
        coverage_status=CoverageStatus.VERIFIED,
        last_verified_date=date(2026, 9, 8),
        verification_evidence="Verified live HTTP 200 API response via federalregister.gov/api/v1/documents.json on 2026-09-08.",
        known_limitations=("Proposed rules (NPRM) are non-binding agency proposals until final rule promulgated.",),
    ),
)


def get_canonical_sources() -> tuple[SourceDefinition, ...]:
    return WISCONSIN_SOURCES + MINNESOTA_SOURCES + FEDERAL_OVERLAY_SOURCES


def build_canonical_registry() -> JurisdictionSourceRegistry:
    return JurisdictionSourceRegistry(
        registry_id="nora-jurisdiction-registry-v1",
        sources=get_canonical_sources(),
    )
